'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs'),crypto=require('node:crypto');
const D=require('../demand-core.js'),X=require('../vendor/xlsx.full.min.js');
const c={window:{},document:{addEventListener(){},querySelector(){return null},querySelectorAll(){return[]}},console};
for(const file of ['curriculum-data.js','student-data-model.js','topic-data.js','admission-pages.js','app.js'])vm.runInNewContext(fs.readFileSync(require('node:path').join(__dirname,'..',file),'utf8'),c);
const model=c.window.ANJWA_STUDENT_MODEL.curriculum.plans;
const ctx={surveyId:'test',round:'1',planKey:'incoming2026',grade:'2',version:'test-version',groups:D.groups(model.incoming2026,'2')};
function response(number='99001'){return {format:D.format,schema:1,responseId:crypto.randomUUID(),exportedAt:'2026-10-05T10:00:00Z',...ctx,groups:undefined,studentNumber:number,name:'가상학생',status:'active',answers:ctx.groups.map(g=>({groupId:g.id,decision:'decided',primary:g.courses.slice(0,g.count).map(c=>c.id),alternative:[],conditions:Object.fromEntries(g.courses.slice(0,g.count).filter(c=>c.deliveryMode==='online'||c.offeringStatus==='review').map(c=>[c.id,'possible']))}))};}
const fileContext={AnjwaDemand:D,XLSX:X,TextEncoder,TextDecoder,Blob,console};vm.createContext(fileContext);vm.runInContext(fs.readFileSync(require('node:path').join(__dirname,'../demand-files.js'),'utf8'),fileContext);const F=fileContext.AnjwaDemandFiles;
test('demand groups exactly match existing curriculum groups in all cohort terms',()=>{for(const [key,plan]of Object.entries(model).filter(([key])=>/^incoming/.test(key)))for(const grade of ['2','3']){const expected=vm.runInNewContext(`['1','2'].flatMap(sem=>buildCurriculumChoiceGroupsForSemester(curriculumData.plans.${key}.courses,'${grade}-'+sem)).map(g=>[g.id,g.courses.map(c=>c.id)])`,c);assert.equal(JSON.stringify(D.groups(plan,grade).map(g=>[g.id,g.courses.map(c=>c.id)])),JSON.stringify(expected));}});
test('XLSX round trip preserves identifier strings, choices, names and print settings',()=>{const r=response('09901');r.name='=가상 이름';const bytes=F.bytes(F.workbook([r],ctx)),records=F.read(bytes,ctx);assert.equal(D.signature(records[0]),D.signature(r));const zip=X.CFB.read(bytes,{type:'buffer'}),xml=new TextDecoder().decode(X.CFB.find(zip,'/xl/worksheets/sheet1.xml').content);assert.match(xml,/fitToWidth="1" fitToHeight="1"/);const wb=X.read(bytes,{type:'array'});assert.equal(wb.Sheets.응답목록.J2.t,'s');assert.ok(!wb.Sheets.응답목록.J2.f);});
test('teacher XLSX restores multiple students and separate conditional/alternative counts',()=>{const a=response(),b=response('99002');const g=ctx.groups.find(g=>g.courses.some(c=>c.deliveryMode==='online'));const ans=b.answers.find(a=>a.groupId===g.id),online=g.courses.find(c=>c.deliveryMode==='online');ans.primary=[online.id,...g.courses.filter(c=>c.id!==online.id).slice(0,g.count-1).map(c=>c.id)];for(const id of ans.primary)if(g.courses.find(c=>c.id===id).deliveryMode==='online')ans.conditions[id]='conditional';ans.alternative=g.courses.filter(c=>!ans.primary.includes(c.id)).slice(0,1).map(c=>c.id);assert.deepEqual(D.validate(b,ctx),[]);const records=F.read(F.bytes(F.workbook([a,b],ctx,true)),ctx),stats=D.aggregate(records,ctx);assert.equal(stats.active,2);assert.equal(stats.stats.find(s=>s.courseId===online.id&&s.groupId===g.id).conditional,1);assert.equal(stats.stats.find(s=>s.courseId===ans.alternative[0]&&s.groupId===g.id).alternative,1);});
test('unknown and withdrawn are valid while invalid choice count, foreign IDs and versions are rejected',()=>{let r=response();r.answers=ctx.groups.map(g=>({groupId:g.id,decision:'unknown',primary:[],alternative:[],conditions:{}}));assert.deepEqual(D.validate(r,ctx),[]);assert.equal(D.aggregate([r],ctx).undecided,1);r.status='withdrawn';assert.equal(D.aggregate([r],ctx).active,0);r=response();r.answers[0].primary=[];assert.ok(D.validate(r,ctx).length);r=response();r.answers[0].primary[0]='foreign';assert.ok(D.validate(r,ctx).length);r=response();r.version='old';assert.throws(()=>F.read(F.bytes(F.workbook([r],ctx)),ctx),/version/);});
test('formula and altered course metadata are rejected before aggregation',()=>{const wb=F.workbook([response()],ctx);wb.Sheets.응답목록.J2={t:'n',v:1,f:'1+1'};assert.throws(()=>F.read(F.bytes(wb),ctx),/수식/);const wb2=F.workbook([response()],ctx);wb2.Sheets.수합데이터.G2={t:'s',v:'틀린 과목'};assert.throws(()=>F.read(F.bytes(wb2),ctx),/과목명/);});
test('different revisions share a survey-student key but changed choices need explicit resolution',()=>{const a=response(),b=response();assert.equal(D.key(a),D.key(b));assert.equal(D.signature(a),D.signature(b));b.status='withdrawn';assert.notEqual(D.signature(a),D.signature(b));b.round='2';assert.notEqual(D.key(a),D.key(b));});

test('sorting data rows does not turn identical choices into different revisions',()=>{const a=response(),b=response();b.answers.reverse();for(const x of b.answers)x.primary.reverse();assert.equal(D.signature(a),D.signature(b));});

test('changes only to the visible application cannot silently leave machine data unchanged',()=>{const wb=F.workbook([response()],ctx);wb.Sheets.신청서.D2={t:'s',v:'다른 이름'};assert.throws(()=>F.read(F.bytes(wb),ctx),/보이는 신청서/);});
