'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs'),crypto=require('node:crypto');
const D=require('../demand-core.js'),X=require('../vendor/xlsx.full.min.js');
const c={window:{},document:{addEventListener(){},querySelector(){return null},querySelectorAll(){return[]}},console};
for(const file of ['curriculum-data.js','student-data-model.js','topic-data.js','admission-pages.js','app.js'])vm.runInNewContext(fs.readFileSync(require('node:path').join(__dirname,'..',file),'utf8'),c);
const model=c.window.ANJWA_STUDENT_MODEL.curriculum.plans;
const ctx={surveyId:'test',round:'1',planKey:'incoming2026',grade:'2',version:'test-version',groups:D.groups(model.incoming2026,'2')};
function response(number='99001'){return {format:D.format,schema:1,responseId:crypto.randomUUID(),exportedAt:'2026-10-05T10:00:00Z',...ctx,groups:undefined,studentNumber:number,name:'가상학생',status:'active',answers:ctx.groups.map(g=>({groupId:g.id,decision:'decided',primary:g.courses.slice(0,g.count).map(c=>c.id),alternative:[],conditions:Object.fromEntries(g.courses.slice(0,g.count).filter(c=>c.deliveryMode==='online'||c.offeringStatus==='review').map(c=>[c.id,'possible']))}))};}
const fileContext={AnjwaDemand:D,XLSX:X,TextEncoder,TextDecoder,Blob,console};vm.createContext(fileContext);vm.runInContext(fs.readFileSync(require('node:path').join(__dirname,'../demand-files.js'),'utf8'),fileContext);const F=fileContext.AnjwaDemandFiles;
test('demand groups exactly match existing curriculum groups in all cohort terms',()=>{for(const [key,plan]of Object.entries(model).filter(([key])=>/^incoming/.test(key)))for(const grade of ['2','3']){const expected=vm.runInNewContext(`['1','2'].flatMap(sem=>buildCurriculumChoiceGroupsForSemester(curriculumData.plans.${key}.courses,'${grade}-'+sem)).map(g=>[g.id,g.courses.map(c=>c.id)])`,c);assert.equal(JSON.stringify(D.groups(plan,grade).map(g=>[g.id,g.courses.map(c=>c.id)])),JSON.stringify(expected));}});
test('XLSX round trip preserves identifier strings, choices, names and print settings',()=>{const r=response('09901');r.name='=가상 이름';const bytes=F.bytes(F.workbook([r],ctx)),records=F.read(bytes,ctx);assert.equal(D.signature(records[0]),D.signature(r));const zip=X.CFB.read(bytes,{type:'buffer'}),xml=new TextDecoder().decode(X.CFB.find(zip,'/xl/worksheets/sheet1.xml').content);assert.match(xml,/fitToWidth="1" fitToHeight="1"/);const wb=X.read(bytes,{type:'array'});assert.equal(wb.Sheets.응답목록.J2.t,'s');assert.ok(!wb.Sheets.응답목록.J2.f);});
test('teacher XLSX restores multiple students and separate conditional/alternative counts',()=>{const a=response(),b=response('99002');const g=ctx.groups.find(g=>g.courses.some(c=>c.deliveryMode==='online'));const ans=b.answers.find(a=>a.groupId===g.id),online=g.courses.find(c=>c.deliveryMode==='online');ans.primary=[online.id,...g.courses.filter(c=>c.id!==online.id).slice(0,g.count-1).map(c=>c.id)];for(const id of ans.primary)if(g.courses.find(c=>c.id===id).deliveryMode==='online')ans.conditions[id]='conditional';ans.alternative=g.courses.filter(c=>!ans.primary.includes(c.id)).slice(0,1).map(c=>c.id);assert.deepEqual(D.validate(b,ctx),[]);const records=F.read(F.bytes(F.workbook([a,b],ctx,true)),ctx),stats=D.aggregate(records,ctx);assert.equal(stats.active,2);assert.equal(stats.stats.find(s=>s.courseId===online.id&&s.groupId===g.id).conditional,1);assert.equal(stats.stats.find(s=>s.courseId===ans.alternative[0]&&s.groupId===g.id).alternative,1);});
test('unknown and withdrawn are valid while invalid choice count, foreign IDs and versions are rejected',()=>{let r=response();r.answers=ctx.groups.map(g=>({groupId:g.id,decision:'unknown',primary:[],alternative:[],conditions:{}}));assert.deepEqual(D.validate(r,ctx),[]);assert.equal(D.aggregate([r],ctx).undecided,1);r.status='withdrawn';assert.equal(D.aggregate([r],ctx).active,0);r=response();r.answers[0].primary=[];assert.ok(D.validate(r,ctx).length);r=response();r.answers[0].primary[0]='foreign';assert.ok(D.validate(r,ctx).length);r=response();r.version='old';assert.throws(()=>F.read(F.bytes(F.workbook([r],ctx)),ctx),/version/);});
test('formula and altered course metadata are rejected before aggregation',()=>{const wb=F.workbook([response()],ctx);wb.Sheets.응답목록.J2={t:'n',v:1,f:'1+1'};assert.throws(()=>F.read(F.bytes(wb),ctx),/수식/);const wb2=F.workbook([response()],ctx);wb2.Sheets.수합데이터.G2={t:'s',v:'틀린 과목'};assert.throws(()=>F.read(F.bytes(wb2),ctx),/과목명/);});
test('different revisions share a survey-student key but changed choices need explicit resolution',()=>{const a=response(),b=response();assert.equal(D.key(a),D.key(b));assert.equal(D.signature(a),D.signature(b));b.status='withdrawn';assert.notEqual(D.signature(a),D.signature(b));b.round='2';assert.notEqual(D.key(a),D.key(b));});

test('sorting data rows does not turn identical choices into different revisions',()=>{const a=response(),b=response();b.answers.reverse();for(const x of b.answers)x.primary.reverse();assert.equal(D.signature(a),D.signature(b));});

test('changes only to the visible application cannot silently leave machine data unchanged',()=>{const wb=F.workbook([response()],ctx);wb.Sheets.신청서.D2={t:'s',v:'다른 이름'};assert.throws(()=>F.read(F.bytes(wb),ctx),/보이는 신청서/);});

test('portable files keep all candidates and load without the installed curriculum',()=>{const portable=D.snapshot(ctx),r={...response(),schema:2},wb=F.workbook([r],portable),bundle=F.readBundle(F.bytes(wb));assert.equal(bundle.source,'embedded');assert.equal(D.contextKey(bundle.context),D.contextKey(portable));assert.equal(D.signature(bundle.records[0]),D.signature(r));assert.equal(bundle.context.groups.reduce((n,g)=>n+g.courses.length,0),ctx.groups.reduce((n,g)=>n+g.courses.length,0));assert.equal(D.aggregate(bundle.records,bundle.context).stats.length,ctx.groups.reduce((n,g)=>n+g.courses.length,0));});
test('new subjects and changed credits survive collection and restore, separately from old versions',()=>{const changed=D.snapshot(ctx);changed.version='future-version';const group=changed.groups[0];group.credits=group.count*5;for(const c of group.courses)c.credits=5;group.courses.push({...group.courses[0],id:'future-course',name:'새로운 가상 과목'});const r={...response(),schema:2,version:changed.version};r.answers[0].primary[0]='future-course';assert.deepEqual(D.validate(r,changed),[]);const b=F.readBundle(F.bytes(F.workbook([r],changed)));assert.equal(b.context.groups[0].courses.at(-1).name,'새로운 가상 과목');assert.equal(D.aggregate(b.records,b.context).stats.find(s=>s.courseId==='future-course').primary,1);assert.notEqual(D.contextKey(b.context),D.contextKey(ctx));assert.throws(()=>F.read(F.bytes(F.workbook([r],changed)),ctx),/편성/);const saved=F.readBundle(F.bytes(F.workbook(b.records,b.context,true)));assert.equal(D.contextKey(saved.context),D.contextKey(changed));assert.equal(D.signature(saved.records[0]),D.signature(r));});
test('portable files reject missing snapshots, wrong budgets, duplicate offerings and formula metadata',()=>{const make=()=>F.workbook([{...response(),schema:2}],ctx);let wb=make();delete wb.Sheets.교육과정;wb.SheetNames=wb.SheetNames.filter(n=>n!=='교육과정');assert.throws(()=>F.readBundle(F.bytes(wb)),/누락/);wb=make();wb.Sheets.교육과정.M2={t:'n',v:99};assert.throws(()=>F.readBundle(F.bytes(wb)),/학점/);wb=make();wb.Sheets.교육과정.G2={t:'s',v:'이름만 변경'};assert.throws(()=>F.readBundle(F.bytes(wb)),/과목명/);wb=make();wb.Sheets.편성정보.B2={t:'s',v:'x',f:'1+1'};assert.throws(()=>F.readBundle(F.bytes(wb)),/수식/);const snap=D.snapshot(ctx);snap.groups[0].courses.push({...snap.groups[0].courses[0]});assert.ok(D.validateContext(snap).length);});
test('legacy files require matching fallback and upgrade to a self-contained teacher file',()=>{const legacy=F.bytes(F.workbook([response()],ctx,true));assert.throws(()=>F.readBundle(legacy),/구형/);const old=F.readBundle(legacy,ctx);assert.equal(old.source,'legacy');assert.throws(()=>F.readBundle(legacy,{...ctx,version:'changed'}),/version/);const saved=F.readBundle(F.bytes(F.workbook(old.records.map(r=>({...r,schema:2})),old.context,true)));assert.equal(saved.source,'embedded');assert.equal(D.signature(saved.records[0]),D.signature(response('99001')));});

test('every supported cohort can export portable candidate lists; invalid operating labels are rejected',()=>{for(const key of ['incoming2025','incoming2026','incoming2027'])for(const grade of ['2','3']){const context={...ctx,planKey:key,grade,groups:D.groups(model[key],grade)},r={...response(),schema:2,planKey:key,grade,answers:context.groups.map(g=>({groupId:g.id,decision:'unknown',primary:[],alternative:[],conditions:{}}))};const b=F.readBundle(F.bytes(F.workbook([r],context)));assert.equal(D.contextKey(b.context),D.contextKey(context));}const bad=D.snapshot(ctx);bad.groups[0].courses[0].offeringStatus='unavailable';assert.ok(D.validateContext(bad).length);});
