'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs'),path=require('node:path');
function harness(){const animations=[],listeners={},media={matches:false,addEventListener(type,fn){listeners[type]=fn}},views=new Map();for(const id of ['home','planner','curriculum'])views.set(id,{children:[],querySelectorAll(){return[]},getBoundingClientRect(){return{left:0,width:100}},classList:{contains(){return true}},animate(frames,options){const item={frames,options,cancelled:false,cancel(){this.cancelled=true},finished:new Promise(()=>{})};animations.push(item);return item}});const c={window:{innerHeight:900,innerWidth:1000,matchMedia(){return media},addEventListener(type,fn){listeners[type]=fn}},document:{getElementById(id){return views.get(id)}},Element:{prototype:{animate(){}}},clearTimeout,setTimeout};vm.runInNewContext(fs.readFileSync(path.join(__dirname,'../motion.js'),'utf8'),c);return{motion:c.window.AnjwaMotion,animations,media,listeners,views};}
test('motion cancellation clears an active effect without invoking navigation or storage',()=>{const h=harness();h.motion.begin('home','planner')();assert.equal(h.animations.length,1);h.motion.cancel();assert.equal(h.animations[0].cancelled,true);h.motion.cancel();});
test('reduced motion and restored routes bypass animation',()=>{const h=harness();h.media.matches=true;assert.equal(h.motion.begin('home','planner'),null);h.media.matches=false;assert.equal(h.motion.begin('home','planner',false),null);assert.equal(h.motion.begin('home','home'),null);assert.equal(h.animations.length,0);});
test('a newer route cancels the older effect and ignores an obsolete completion',()=>{const h=harness(),old=h.motion.begin('home','planner'),next=h.motion.begin('home','curriculum');old();assert.equal(h.animations.length,0);next();assert.equal(h.animations.length,1);const restore=h.motion.begin('curriculum','home',false);assert.equal(restore,null);assert.equal(h.animations[0].cancelled,true);});
test('preference changes and page exit stop presentation effects',()=>{const h=harness();h.motion.begin('home','planner')();h.listeners.change();assert.equal(h.animations[0].cancelled,true);h.motion.begin('planner','curriculum')();h.listeners.pagehide();assert.equal(h.animations[1].cancelled,true);});

test('visible destination elements assemble in sequence and cancel together',()=>{const h=harness(),base=h.views.get('planner');const make=left=>({getBoundingClientRect(){return{left,width:100,height:100,top:10,bottom:110}},contains(){return false},animate:base.animate});base.querySelectorAll=()=>[make(0),make(700)];h.motion.begin('home','planner')();assert.equal(h.animations.length,2);assert.equal(h.animations[0].options.delay,0);assert.equal(h.animations[1].options.delay,42);assert.equal(h.animations[0].options.fill,'backwards');assert.equal(h.animations[0].frames.at(-1).opacity,1);h.motion.cancel();assert.ok(h.animations.every(a=>a.cancelled));});
